// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://riykcdgldcphjntuiihl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpeWtjZGdsZGNwaGpudHVpaWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NjY5NDUsImV4cCI6MjA3MzM0Mjk0NX0.Vn3B_4IFWTJQ2Jo-PI8Jbtfze3a2g8rFD3PnW9o2dVM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});